### ISSUE TITLE
Better Implementation

### ISSUE THREAD

**Issue by TinyPandas** [TinyPandas/AnnotationLoader#3]
The current implementation binds the main class to `extends AnnotationLoader`. This prevents the end user from using any other library that may require the main class extending some other class.

Solution:
- Find a better method to invoke `onStartRegister` before / or with `main`.
or
- Draft a lifecycle and have the user invoke the methods at their discretion.

### Solution

Design a lifecycle ideology out of box.
- [ ] Have `@OnStart` and `@OnStop`
- [ ] Have `onStartRegsiter` and `onStopRegister` in `AnnotationLoader`

With the new implementation:
- [ ] Allow end users to describe their own stages and annotations
- [ ] A user can create a new annotation and loader it to `AnnotationLoader`

For users who might require true on start registering:
- [ ] Allow extension to happen on any class, vs their main class
  - example: `Main.class` would instantiate `Start.class` which would `extends AnnotationLoader` and be deemed as the _start_ location.

**Comment by Dame-G** [comment]
Why is it required to prevent an end user from using other libraries that require the main one?

**Comment by TinyPandas** [comment]
Will be reworked entirely in v2.x.y
